### ISSUE TITLE
OwnerCommand does not works as intended

### ISSUE THREAD

**Issue by Artuto** [jagrosh/JDA-Utilities#24] opened 2017-07-30 07:42 UTC
Okay so... My eval command is ownerOnly (by obvious reasons) so I added my alt as a CoOwner, but when I try to run the command I cant. The snowflake is correct (I checked it with the bot and the Discord right click > copy id. Tomorrow I'll add screenshots and some code since right now there is 02:41 am.

PST: Sorry for any word mispelled, 2:42 am, a tablet and 5% of battery left.

**Comment by Shengaero** [comment] 2017-07-30 07:51
When you are able to, a snippet of code where you set the ID would help too.

Also make sure you are running the newest version (1.3) and have replicated the bug more than once.

**Comment by jagrosh** [comment] 2017-07-30 07:51
~~The fix for this will be out in 1.4, which should be releasing soon~~ nevermind

**Comment by Artuto** [comment] 2017-07-30 23:53
Okay so, I'm here. This is on my main class where I set the CoOwnerID:

```client.setCoOwnerIds(Config.getCoOwnerId());```

Config:

```coownerid=302534881370439681```

![heh](http://i.artuto.me/2017-07-30_18-40-25.png)

The bot replies because I added a check to the code:

```
if(!(event.isOwner()) || event.isCoOwner())
   {
        event.replyError("Sorry, but you don't have access to this command! Only Bot owners!");
        return;
   }
```

But with ```this.ownerCommand = true;``` does the same, cancells the command.

**Comment by Shengaero** [comment] 2017-07-31 01:58
The check you posted would obviously fail for CoOwners because the condition is:

"if the event **is not** from the Owner, or **is** from a CoOwner."

However, you say that the command also fails when `ownerCommand` is set to `true`.

I am, however, unable to reproducible this issue on my end.
If you have not already, I'd advise you to update to 1.4 and try to reproduce it there.

If you do, a link to a git repository containing the code this occurs in would be very much appreciated, as I am unable to determine where the issue may be occurring through snippets alone

**Comment by Artuto** [comment] 2017-07-31 03:25
I'll update to 1.4 and see whats happens

**Comment by Artuto** [comment] 2017-07-31 03:49
Okay, after updating to 1.4 works fine!

BTW, is possible I can add a response when the Command isn't executed by a Co Owner or the owner?

Thanks in advance.

**Comment by Shengaero** [comment] 2017-07-31 03:52
I'd recommend a category in place of using `guildOnly = true` if you wish to provide an error.
Not to sound rude, but I think [we've already discussed this](https://github.com/JDA-Applications/JDA-Utilities/issues/15) 😅

**Closed as completed by Shengaero** 2017-07-31 03:52 UTC
Labels: Bug
