### ISSUE TITLE
FinderUtil issue

### ISSUE THREAD

**Issue by Artuto** [jagrosh/JDA-Utilities#26] opened 2017-08-02 15:58 UTC
(Yes, me again) Using FinderUtils I noticed when someone has a Nickname on a Guild if you try to get a user just doing for example /user artuto, the list will be empty, unless the user doesnt has a nickname, but you can do /user artuto's nickname.

Could this be an issue or is intended?

**Comment by Artuto** [comment] 2017-08-02 16:01
And yeah I clicked the send button without writing anything. xD

**Comment by Shengaero** [comment] 2017-08-02 16:22
I can confirm this is something that occurs.

I believe this is due to the fact that `FinderUtil#findMembers(String, Guild)` looks for matches to the query based on `Member#getEffectiveName()` and not something like `Member#getUser().getName()`, but I'll need to look into it.

Whether we "fix" this or not is up in the air, but if we do, it will be in ~~1.5~~ (I apologize, I forgot to commit changes to fix this, 1.6 will have it).

**Comment by Shengaero** [comment] 2017-08-27 05:01
Fixed For 1.6 (#29)

**Closed as completed** 2017-08-27 05:01 UTC
