### ISSUE TITLE
CommandClientBuilder: UnirestException - ClassDefNotFoundException

### ISSUE THREAD

**Issue by paulhlschr** [jagrosh/JDA-Utilities#19] opened 2017-07-20 12:17 UTC
Can't build the client (`client.build()`).

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/mashape/unirest/http/exceptions/UnirestException
	at com.jagrosh.jdautilities.commandclient.CommandClientBuilder.build(CommandClientBuilder.java:63)
Caused by: java.lang.ClassNotFoundException: com.mashape.unirest.http.exceptions.UnirestException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

**Comment by Artuto** [comment] 2017-07-21 04:19
It would be helpful if you share the code.

**Comment by Shengaero** [comment] 2017-07-21 04:47
What version of JDA are you running this on?

**Comment by jagrosh** [comment] 2017-07-21 05:36
The problem is the missing pom; we're working on resolving this

**Closed as completed** 2017-07-28 09:25 UTC
